apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: local.worker
  name: local.worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: local.worker
    spec:
      containers:
      - args:
        - /bin/bash
        - run.sh
        image: nameko/local.worker
        name: nameko.local.worker
        resources: {}
      restartPolicy: Always
status: {}
